jdk 1.4 build fixes.  Fixed permission checks.  win32 build fixes.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -192,15 +192,15 @@ fix_parameters()
 		echo "echo \"Driver=gnu.io.RXTXCommDriver\" > $1" 1>&2
 		echo 1>&2
 		echo "------------------------------------------------------" 1>&2
-		if [ test -w $1 ]; then
-			echo $ac_n "Is it ok to place it there now? [[y/n]] "
-			read REPLY
-			if [ test "$REPLY" = "y" || test "$REPLY" = "Y" ];then 1>&2
-				echo "Driver=gnu.io.RXTXCommDriver" > $1; 1>&2
-			fi;
-		else
-			echo "However, we don't have proper permissions, so please do it yourself";
+		echo $ac_n "Is it ok to place it there now? [[y/n]] "
+		read REPLY
+		if [ test "$REPLY" = "y" || test "$REPLY" = "Y" ];then 1>&2
+			echo "Driver=gnu.io.RXTXCommDriver" > $1; 1>&2
+		fi;
+		if [ ! test -w $1 ]; then
+			echo "However, we don't have proper permissions, so please do it as root";
 			echo "*******************************************************************";
+			exit
 		fi;
 	fi;
 }
@@ -386,41 +386,39 @@ fix_comm_jar()
 		echo "correct location or let this script do it." 1>&2
 		echo  1>&2
 		echo "------------------------------------------------------" 1>&2
-		if test -w $1; then
-			echo $ac_n "Do you wish to [[Q]]uit or use the [[S]]cript? [[Q/S]] "
-			read REPLY
-			if [ test "$REPLY" = "q" || test "$REPLY" = "Q" ];then
-				echo "When you are done rerun configure"
-				exit
-			else if [ test "$REPLY" = "s" || test "$REPLY" = "S" ];then
-				FILE="null"
-				until test -f $FILE;do
-					echo "Please enter the full path to comm.jar (example /home/jarvi/tools/commapi/comm.jar):"
-					read FILE
-				done;
-				if grep -q Win32 $FILE;then 
-					echo 1>&2
-					echo WARNING: 1>&2
-					echo 1>&2
-					echo "I've detected A Windows version of comm.jar.   This is known to not work with"  1>&2
-					echo "rxtx on UNIX.  Go to  http://java.sun.com/products/javacomm/index.html and " 1>&2
-					echo "get the solaris-x86 CommAPI if your target is unix."  1>&2
-					echo  1>&2
-					echo "Press enter to continue."
-					read REPLY
-				fi 
-				echo $ac_n "Is it ok to copy $FILE to $1?[[y/n]] "
-				read REPLY
-				if [ test "$REPLY" = "y" || test "$REPLY" = "Y" ];then
-					cp $FILE $1
-					return
-				fi;
-			fi;fi;
-			echo "configure is unable to continue.  Please try again or manual fix the problem." 1>&2
+		echo $ac_n "Do you wish to [[Q]]uit or use the [[S]]cript? [[Q/S]] "
+		read REPLY
+		if [ test "$REPLY" = "q" || test "$REPLY" = "Q" ];then
+			echo "When you are done rerun configure"
 			exit
-		else
-			echo "However, we don't have proper permissions, so please do it yourself";
+		else if [ test "$REPLY" = "s" || test "$REPLY" = "S" ];then
+			FILE="null"
+			until test -f $FILE;do
+				echo "Please enter the full path to comm.jar (example /home/jarvi/tools/commapi/comm.jar):"
+				read FILE
+			done;
+			if grep -q Win32 $FILE;then 
+				echo 1>&2
+				echo WARNING: 1>&2
+				echo 1>&2
+				echo "I've detected A Windows version of comm.jar.   This is known to not work with"  1>&2
+				echo "rxtx on UNIX.  Go to  http://java.sun.com/products/javacomm/index.html and " 1>&2
+				echo "get the solaris-x86 CommAPI if your target is unix."  1>&2
+				echo  1>&2
+				echo "Press enter to continue."
+				read REPLY
+			fi 
+			echo $ac_n "Is it ok to copy $FILE to $1?[[y/n]] "
+			read REPLY
+			if [ test "$REPLY" = "y" || test "$REPLY" = "Y" ];then
+				cp $FILE $1
+			fi;
+		fi;fi;
+		if [ ! test -w $1 ]; then
+			echo "However, we don't have proper permissions, so please do it as root";
 			echo "*******************************************************************";
+			echo "configure is unable to continue.  Please try again or manually fix the problem." 1>&2
+			exit
 		fi;
 	
 	fi;
@@ -627,7 +625,7 @@ BeOS)
 
 WIN32)
 	case $JAVA_VERSION in
-	1.2*|1.3*)
+	1.2*|1.3*|1.4*)
 		CLASSPATH="-classpath .:\$(TOP):\$(TOP)/src:`find $JPATH/ -name comm.jar |head -n1`:$CLASSPATH"
 		JHOME=$JPATH"/jre/lib/ext"
 	;;
