merged win32 fixes from 1.5 cleanup of ParallelImp.c eventLoop (more needed) merged documentation changes from 1.5 that are related.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -151,6 +151,27 @@ echo $ac_n checking os.version   " " 1>&6
 OS_VERSION=`uname -r`
 echo $OS_VERSION 1>&6
 
+fix_parameters()
+{
+	if [ ! grep -q "Driver=gnu.io.RXTXCommDriver" $1 ]; then 
+		echo "------------------------------------------------------" 1>&2
+		echo "RxTx requires the following information in" 1>&2
+		echo " $1:" 1>&2
+		echo 1>&2
+		echo "Driver=gnu.io.RXTXCommDriver" 1>&2
+		echo 1>&2
+		echo "The command configure will use to fix this is:" 1>&2
+		echo 1>&2
+		echo "echo \"Driver=gnu.io.RXTXCommDriver\" > $1" 1>&2
+		echo 1>&2
+		echo "------------------------------------------------------" 1>&2
+		echo $ac_n "Is it ok to place it there now? [[y/n]] "
+		read REPLY
+		if [ test "$REPLY" = "y" || test "$REPLY" = "Y" ];then 1>&2
+			echo "Driver=gnu.io.RXTXCommDriver" > $1; 1>&2
+		fi;
+	fi;
+}
 check_prefix()
 {
 	if test $prefix != "/usr";then 
@@ -159,6 +180,8 @@ check_prefix()
 		echo "          Unless /usr/local/lib or the specified prefix is in"  1>&2
 		echo "          the linkers path this will cause problems later on." 1>&2
 		echo 1>&2
+		echo "          Press enter to continue."
+		read  REPLY
 	fi
 }
 # an attempt to compile on libc5 linux machines
@@ -323,14 +346,48 @@ EOF
 }
 fix_comm_jar()
 {
-	if test -f $1;then
+	if ! test -f $1;then
 		echo "------------------------------------------------------" 1>&2
-		echo "WARNING:  A comm.jar file is alread installed" 1>&2
-		echo "make install will overwrite it" 1>&2
+		echo "The JCL extension to RxTx requires comm.jar" 1>&2
+		echo "If you intend to use RxTx for commapi support comm.jar" 1>&2
+		echo "needs to be located in $1" 1>&2
 		echo 1>&2
-		echo $1
-		echo 1>&2
+		echo "You can either quit configure and place the jar in the" 1>&2
+		echo "correct location or let this script do it." 1>&2
+		echo  1>&2
 		echo "------------------------------------------------------" 1>&2
+		echo $ac_n "Do you wish to [[Q]]uit or use the [[S]]cript? [[Q/S]] "
+		read REPLY
+		if [ test "$REPLY" = "q" || test "$REPLY" = "Q" ];then
+			echo "When you are done rerun configure"
+			exit
+		else if [ test "$REPLY" = "s" || test "$REPLY" = "S" ];then
+			FILE="null"
+			until test -f $FILE;do
+				echo "Please enter the full path to comm.jar (example /home/jarvi/tools/commapi/comm.jar):"
+				read FILE
+			done;
+			if grep -q Win32 $FILE;then 
+				echo 1>&2
+				echo WARNING: 1>&2
+				echo 1>&2
+				echo "I've detected A Windows version of comm.jar.   This is known to not work with"  1>&2
+				echo "rxtx on UNIX.  Go to  http://java.sun.com/products/javacomm/index.html and " 1>&2
+				echo "get the solaris-x86 CommAPI if your target is unix."  1>&2
+				echo  1>&2
+				echo "Press enter to continue."
+				read REPLY
+			fi 
+			echo $ac_n "Is it ok to copy $FILE to $1?[[y/n]] "
+			read REPLY
+			if [ test "$REPLY" = "y" || test "$REPLY" = "Y" ];then
+				cp $FILE $1
+				return
+			fi;
+		fi;fi;
+		echo "configure is unable to continue.  Please try again or manual fix the problem." 1>&2
+		exit
+	
 	fi;
 }
 
@@ -370,7 +427,7 @@ fi
 if [ test -d $JPATH/share/kaffe/ ]
 	then fix_comm_jar $JPATH/share/kaffe/comm.jar
 elif [ test -d $JPATH/jre/lib/ext ]
-	then fix_comm_jar $JPATH/lib/ext/comm.jar
+	then fix_comm_jar $JPATH/jre/lib/ext/comm.jar
 elif [ test -d $JPATH/lib ] 
 	then fix_comm_jar $JPATH/lib/comm.jar
 fi
@@ -380,12 +437,15 @@ Linux)
 	check_java_headers
 	case $JAVA_VERSION in
 	1.2*|1.3*) 
-		#fix_parameters $JPATH/jre/lib/javax.comm.properties
+		fix_parameters $JPATH/jre/lib/javax.comm.properties
+		fix_comm_jar $JPATH/jre/lib/ext/comm.jar
 		CLASSPATH="-classpath .:\$(TOP):\$(TOP)/src:"`find $JPATH/ -name comm.jar |head -n1`
 		JHOME=$JPATH"/jre/lib/ext"
 		RXTX_PATH="\$(JPATH)/jre/lib/\$(OS_ARCH)"
 	;;
 	1.*) 
+		fix_parameters $JPATH/lib/javax.comm.properties
+		fix_comm_jar $JPATH/lib/comm.jar
 		CLASSPATH="-classpath .:\$(TOP):\$(TOP)/src:"` \
 			if [ -d $JPATH/share/kaffe/ ]; then
 				find $JPATH/share/kaffe/ -name [cK]lasses.[jz][ai][rp]
@@ -412,10 +472,14 @@ Linux)
 	TARGETLIB="\$(target_alias)/libSerial.la"
 	case $JAVA_VERSION in
 	1.2*) 
+		fix_parameters $JPATH/jre/lib/javax.comm.properties
+		fix_comm_jar $JPATH/jre/lib/ext/comm.jar
 		CLASSPATH="-classpath .:\$(TOP):\$(TOP)/src:$CLASSPATH"
 	;;
 	1.*) 
 		check_prefix
+		fix_parameters $JPATH/lib/javax.comm.properties
+		fix_comm_jar $JPATH/lib/comm.jar
 	;;
 	*)
 	;;
@@ -436,11 +500,15 @@ HP-UX)
 	case $JAVA_VERSION in
 		HP-UX\ Java\ C.01.18*) 
 			echo I\'m in $JAVA_VERSION
+			fix_parameters $JPATH/lib/javax.comm.properties
+			fix_comm_jar $JPATH/lib/comm.jar
 			JHOME=$JPATH/"lib"
 			CLASSPATH="-classpath .:\$(TOP):\$(TOP)/src:\$(JPATH)/lib/classes.zip:\$(JPATH)/lib/comm.jar:$CLASSPATH"
 			RXTX_PATH="\$(prefix)/lib/"
 		;;
 		*)
+			fix_parameters $JPATH/lib/javax.comm.properties
+			fix_comm_jar $JPATH/lib/comm.jar
 			JHOME=$JPATH/"lib"
 			CLASSPATH="-classpath .:\$(TOP):\$(TOP)/src:\$(JPATH)/lib/classes.zip:\$(JPATH)/lib/comm.jar:$CLASSPATH"
 			RXTX_PATH="\$(prefix)/lib/"
